### ISSUE TITLE
Hangs on `Starting mesos slave mesos-jenkins`

### ISSUE THREAD

**Issue by ryankennedyio** [mesosphere/jenkins-dcos#117]
Hi,

We've set up a Jenkins service on a DCOS cluster (running from a 1.9 dev release), however none of the jenkins slave agents get launched, hanging on `Starting mesos slave mesos-jenkins-3a192fdee4f94782a26bcc8fd097cc65`.

This happens both through installation from https://github.com/mesosphere/cd-demo as well as normal DC/OS UI installation. It happens with standard freestyle jobs and the `dynamic-agents` task from the `cd-demo`.

I feel like it might be that Mesos is not offering enough resources to launch a new slave? I can confirm there are enough resources available on a single host for the agents to be launched.

**Comment by colin-msphere** [comment]
Can you check the Jenkins logs for errors related to mesos such as `TASK_KILLED`, `TASK_FAILED`, or stack traces around agent provisioning? 

From within Jenkins: `Manage Jenkins` > `System Log` > `All Jenkins Logs`.

**Comment by ssk2** [comment]
Do you see tasks being launched in the Mesos UI? (Reachable at http://<dcos-host>/master)

**Comment by ssk2** [comment]
@ryankennedyio: closing this for now but please re-open if you have more information to hand.
