### ISSUE TITLE
Custom URL?

### ISSUE THREAD

**Issue by tystr** [mesosphere/jenkins-dcos#76]
I hope this is the correct place to ask this question.

Currently when this is installed it's accessible at `http://<dcos-url>/service/jenkins`. I'd like to expose this at some custom url like `http://ci.example.com`.

Adding it to an external loadbalancer with the  `HAPROXY_GROUP` and `HAPROXY_0_VHOST` labels in the marathon application configuration sorta works, but it still just redirects to the `http://<dcos-url>/service/jenkins` url.

Is there some way to configure jenkins to live at a different url?

**Comment by ssk2** [comment]
Can you share your marathon.json? We have this working for https://velocity.mesosphere.com (with the caveat that it still adds on the `/service/velocity` path - which is a known routing bug).

**Comment by tystr** [comment]
Here's the json configuration for the marathon jenkins app. It's mostly defaults with the addition of the haproxy labels:

```JSON
{
  "id": "/jenkins",
  "cmd": null,
  "cpus": 1,
  "mem": 1024,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": [
    "*"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/var/jenkins_home",
        "hostPath": "jenkins",
        "mode": "RW"
      },
      {
        "containerPath": "/opt/mesosphere",
        "hostPath": "/opt/mesosphere",
        "mode": "RO"
      },
      {
        "containerPath": "jenkins",
        "mode": "RW",
        "persistent": {
          "size": 10000
        }
      }
    ],
    "docker": {
      "image": "mesosphere/jenkins:0.2.3",
      "network": "HOST",
      "privileged": false,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "env": {
    "LD_LIBRARY_PATH": "/opt/mesosphere/lib",
    "SSH_KNOWN_HOSTS": "github.com",
    "JENKINS_CONTEXT": "/service/jenkins",
    "JVM_OPTS": "-Xms512m -Xmx512m",
    "JENKINS_MESOS_MASTER": "zk://leader.mesos:2181/mesos",
    "JENKINS_FRAMEWORK_NAME": "jenkins"
  },
  "healthChecks": [
    {
      "path": "/service/jenkins",
      "protocol": "HTTP",
      "portIndex": 0,
      "gracePeriodSeconds": 30,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "labels": {
    "DCOS_PACKAGE_RELEASE": "8",
    "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo",
    "HAPROXY_GROUP": "external",
    "DCOS_PACKAGE_METADATA": "eyJsaWNlbnNlcyI6W3sibmFtZSI6IkFwYWNoZSBMaWNlbnNlIFZlcnNpb24gMi4wIiwidXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL21lc29zcGhlcmUvamVua2lucy1tZXNvcy9ibG9iL21hc3Rlci9MSUNFTlNFIn1dLCJ3ZWJzaXRlIjoiaHR0cHM6Ly9qZW5raW5zLWNpLm9yZyIsIm5hbWUiOiJqZW5raW5zIiwicG9zdEluc3RhbGxOb3RlcyI6IkplbmtpbnMgaGFzIGJlZW4gaW5zdGFsbGVkLiIsInNjbSI6Imh0dHBzOi8vZ2l0aHViLmNvbS9tZXNvc3BoZXJlL2plbmtpbnMtbWVzb3MuZ2l0IiwiZGVzY3JpcHRpb24iOiJKZW5raW5zIGlzIGFuIGF3YXJkLXdpbm5pbmcsIGNyb3NzLXBsYXRmb3JtLCBjb250aW51b3VzIGludGVncmF0aW9uIGFuZCBjb250aW51b3VzIGRlbGl2ZXJ5IGFwcGxpY2F0aW9uIHRoYXQgaW5jcmVhc2VzIHlvdXIgcHJvZHVjdGl2aXR5LiBVc2UgSmVua2lucyB0byBidWlsZCBhbmQgdGVzdCB5b3VyIHNvZnR3YXJlIHByb2plY3RzIGNvbnRpbnVvdXNseSBtYWtpbmcgaXQgZWFzaWVyIGZvciBkZXZlbG9wZXJzIHRvIGludGVncmF0ZSBjaGFuZ2VzIHRvIHRoZSBwcm9qZWN0LCBhbmQgbWFraW5nIGl0IGVhc2llciBmb3IgdXNlcnMgdG8gb2J0YWluIGEgZnJlc2ggYnVpbGQuIEl0IGFsc28gYWxsb3dzIHlvdSB0byBjb250aW51b3VzbHkgZGVsaXZlciB5b3VyIHNvZnR3YXJlIGJ5IHByb3ZpZGluZyBwb3dlcmZ1bCB3YXlzIHRvIGRlZmluZSB5b3VyIGJ1aWxkIHBpcGVsaW5lcyBhbmQgaW50ZWdyYXRpbmcgd2l0aCBhIGxhcmdlIG51bWJlciBvZiB0ZXN0aW5nIGFuZCBkZXBsb3ltZW50IHRlY2hub2xvZ2llcy4iLCJwYWNrYWdpbmdWZXJzaW9uIjoiMi4wIiwidGFncyI6WyJjb250aW51b3VzLWludGVncmF0aW9uIiwiY2kiLCJqZW5raW5zIl0sInBvc3RVbmluc3RhbGxOb3RlcyI6IkplbmtpbnMgaGFzIGJlZW4gdW5pbnN0YWxsZWQuIE5vdGUgdGhhdCBhbnkgZGF0YSBwZXJzaXN0ZWQgdG8gYSBORlMgc2hhcmUgc3RpbGwgZXhpc3RzIGFuZCB3aWxsIG5lZWQgdG8gYmUgbWFudWFsbHkgcmVtb3ZlZC4iLCJtYWludGFpbmVyIjoic3VwcG9ydEBtZXNvc3BoZXJlLmlvIiwic2VsZWN0ZWQiOnRydWUsImZyYW1ld29yayI6dHJ1ZSwidmVyc2lvbiI6IjAuMi4zIiwicHJlSW5zdGFsbE5vdGVzIjoiV0FSTklORzogSmVua2lucyBvbiBEQ09TIGlzIGN1cnJlbnRseSBpbiBCRVRBLiBUaGVyZSBtYXkgYmUgYnVncywgaW5jb21wbGV0ZVxuZmVhdHVyZXMsIGluY29ycmVjdCBkb2N1bWVudGF0aW9uLCBvciBvdGhlciBkaXNjcmVwYW5jaWVzLlxuXG5JZiB5b3UgZGlkbid0IHByb3ZpZGUgYSB2YWx1ZSBmb3IgYGhvc3Qtdm9sdW1lYCBpbiB0aGUgQ0xJLFxuWU9VUiBEQVRBIFdJTEwgTk9UIEJFIFNBVkVEIElOIEFOWSBXQVkuXG4iLCJpbWFnZXMiOnsiaWNvbi1zbWFsbCI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1zbWFsbC5wbmciLCJpY29uLW1lZGl1bSI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1tZWRpdW0ucG5nIiwiaWNvbi1sYXJnZSI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1sYXJnZS5wbmciLCJzY3JlZW5zaG90cyI6bnVsbH19",
    "DCOS_PACKAGE_REGISTRY_VERSION": "2.0",
    "DCOS_PACKAGE_FRAMEWORK_NAME": "jenkins",
    "DCOS_PACKAGE_VERSION": "0.2.3",
    "DCOS_PACKAGE_NAME": "jenkins",
    "MARATHON_SINGLE_INSTANCE_APP": "true",
    "DCOS_PACKAGE_IS_FRAMEWORK": "true",
    "HAPROXY_0_VHOST": "ci.example.com"
  },
  "portDefinitions": [
    {
      "port": 10107,
      "protocol": "tcp",
      "labels": {}
    },
    {
      "port": 10108,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}
```

**Comment by ssk2** [comment]
Ah, I see the problem. You need to set the Jenkins root URL property. This is something that we have in our development package but you'll need to set it manually for now to avoid having Jenkins redirect you back to the master.

You can set this via "Manage Jenkins":
![image](https://cloud.githubusercontent.com/assets/355705/15445031/42cb8f04-1ead-11e6-8e77-a9064771f996.png)

**Comment by ssk2** [comment]
(Note that in your case, you'll have to use  `http://ci.example.com/service/jenkins/`)

**Comment by tystr** [comment]
@ssk2 ah, I'd tried it before without the `/service/jenkins/` and it just broke. I'll give it a go with that bit and see what happens

**Comment by tystr** [comment]
Alright, so setting the custom url in jenkins still did not prevent it from redirecting. Also, after safely restarting jenkins, it is now no longer accessible. This seems to happen any time I change the jenkins root url from the private `10.x.x.x` IP url it has set by default.

**Comment by ssk2** [comment]
@tystr - just to check, you're not changing the URL under Mesos Cloud config are you? (That should remain the same - it's used to register with Mesos as a framework.)

**Comment by tystr** [comment]
@ssk2 correct, I was changing it under the Jenkins Location section:

![Jenkins Location](https://dl.dropboxusercontent.com/spa/fj2qthim0e29gmi/o1qr1m0_.png)

**Comment by joan38** [comment]
I just found out in https://github.com/mesosphere/jenkins-dcos/blob/master/scripts/bootstrap.py that we can set the env JENKINS_ROOT_URL=http://example.com/service/jenkins/

But then I get a 502 Bad Gatway error after restarting the app from Marathon.

FYI I am interested by setting the Jenkins URL because I'm using Google OAuth and this needs to be the public URL. I managed to make it work by setting the public URL from the Jenkins Config panel but it gets overridden at restart of Jenkins.

**Comment by rji** [comment]
At Mesosphere, we use the `root-url` property for our production Jenkins cluster, exposing the public URL as `https://jenkins.mesosphere.com/service/jenkins/`, so that our engineers can authenticate with OneLogin. More information is available in the "Configuration Reference" section of https://docs.mesosphere.com/1.7/usage/service-guides/jenkins/custom-install/.
