### ISSUE TITLE
FileSystemException

### ISSUE THREAD

**Issue by pdiniz13** [mesosphere/jenkins-dcos#81]
I'm getting this error on every load.
Mesos slave(hostname): null
ln builds/lastSuccessfulBuild /var/jenkins_home/workspace/testredis/lastSuccessful failed
java.nio.file.FileSystemException: /var/jenkins_home/workspace/testredis/lastSuccessful: Operation not supported
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createSymbolicLink(UnixFileSystemProvider.java:456)
	at java.nio.file.Files.createSymbolicLink(Files.java:996)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.Util.createSymlinkJava7(Util.java:1237)
	at hudson.Util.createSymlink(Util.java:1153)
	at hudson.model.Run.createSymlink(Run.java:1840)
	at hudson.model.Run.updateSymlinks(Run.java:1821)
	at hudson.model.Run.execute(Run.java:1736)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by ssk2** [comment]
@pdiniz13 where are you seeing this error exactly? (In the Jenkins logs?)

Can you share the details of your environment? What version of DC/OS are you using?

**Comment by pdiniz13** [comment]
This is the current setup

`{
    "id": "/jenkins",
    "cmd": null,
    "cpus": 1,
    "mem": 1024,
    "disk": 0,
    "instances": 1,
    "acceptedResourceRoles": [
        "*"
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/var/jenkins_home",
                "hostPath": "/mnt/data/jenkins/jenkins",
                "mode": "RW"
            },
            {
                "containerPath": "/opt/mesosphere",
                "hostPath": "/opt/mesosphere",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "mesosphere/jenkins:0.2.3",
            "network": "HOST",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "env": {
        "LD_LIBRARY_PATH": "/opt/mesosphere/lib",
        "SSH_KNOWN_HOSTS": "github.com",
        "JENKINS_CONTEXT": "/service/jenkins",
        "JVM_OPTS": "-Xms512m -Xmx512m",
        "JENKINS_MESOS_MASTER": "zk://leader.mesos:2181/mesos",
        "JENKINS_FRAMEWORK_NAME": "jenkins"
    },
    "healthChecks": [
        {
            "path": "/service/jenkins",
            "protocol": "HTTP",
            "portIndex": 0,
            "gracePeriodSeconds": 30,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ignoreHttp1xx": false
        }
    ],
    "labels": {
        "DCOS_PACKAGE_RELEASE": "8",
        "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo-1.7",
        "HAPROXY_GROUP": "external",
        "DCOS_PACKAGE_METADATA": "eyJsaWNlbnNlcyI6W3sibmFtZSI6IkFwYWNoZSBMaWNlbnNlIFZlcnNpb24gMi4wIiwidXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL21lc29zcGhlcmUvamVua2lucy1tZXNvcy9ibG9iL21hc3Rlci9MSUNFTlNFIn1dLCJ3ZWJzaXRlIjoiaHR0cHM6Ly9qZW5raW5zLWNpLm9yZyIsIm5hbWUiOiJqZW5raW5zIiwicG9zdEluc3RhbGxOb3RlcyI6IkplbmtpbnMgaGFzIGJlZW4gaW5zdGFsbGVkLiIsInNjbSI6Imh0dHBzOi8vZ2l0aHViLmNvbS9tZXNvc3BoZXJlL2plbmtpbnMtbWVzb3MuZ2l0IiwiZGVzY3JpcHRpb24iOiJKZW5raW5zIGlzIGFuIGF3YXJkLXdpbm5pbmcsIGNyb3NzLXBsYXRmb3JtLCBjb250aW51b3VzIGludGVncmF0aW9uIGFuZCBjb250aW51b3VzIGRlbGl2ZXJ5IGFwcGxpY2F0aW9uIHRoYXQgaW5jcmVhc2VzIHlvdXIgcHJvZHVjdGl2aXR5LiBVc2UgSmVua2lucyB0byBidWlsZCBhbmQgdGVzdCB5b3VyIHNvZnR3YXJlIHByb2plY3RzIGNvbnRpbnVvdXNseSBtYWtpbmcgaXQgZWFzaWVyIGZvciBkZXZlbG9wZXJzIHRvIGludGVncmF0ZSBjaGFuZ2VzIHRvIHRoZSBwcm9qZWN0LCBhbmQgbWFraW5nIGl0IGVhc2llciBmb3IgdXNlcnMgdG8gb2J0YWluIGEgZnJlc2ggYnVpbGQuIEl0IGFsc28gYWxsb3dzIHlvdSB0byBjb250aW51b3VzbHkgZGVsaXZlciB5b3VyIHNvZnR3YXJlIGJ5IHByb3ZpZGluZyBwb3dlcmZ1bCB3YXlzIHRvIGRlZmluZSB5b3VyIGJ1aWxkIHBpcGVsaW5lcyBhbmQgaW50ZWdyYXRpbmcgd2l0aCBhIGxhcmdlIG51bWJlciBvZiB0ZXN0aW5nIGFuZCBkZXBsb3ltZW50IHRlY2hub2xvZ2llcy4iLCJwYWNrYWdpbmdWZXJzaW9uIjoiMi4wIiwidGFncyI6WyJjb250aW51b3VzLWludGVncmF0aW9uIiwiY2kiLCJqZW5raW5zIl0sInBvc3RVbmluc3RhbGxOb3RlcyI6IkplbmtpbnMgaGFzIGJlZW4gdW5pbnN0YWxsZWQuIE5vdGUgdGhhdCBhbnkgZGF0YSBwZXJzaXN0ZWQgdG8gYSBORlMgc2hhcmUgc3RpbGwgZXhpc3RzIGFuZCB3aWxsIG5lZWQgdG8gYmUgbWFudWFsbHkgcmVtb3ZlZC4iLCJtYWludGFpbmVyIjoic3VwcG9ydEBtZXNvc3BoZXJlLmlvIiwic2VsZWN0ZWQiOnRydWUsImZyYW1ld29yayI6dHJ1ZSwidmVyc2lvbiI6IjAuMi4zIiwicHJlSW5zdGFsbE5vdGVzIjoiV0FSTklORzogSmVua2lucyBvbiBEQ09TIGlzIGN1cnJlbnRseSBpbiBCRVRBLiBUaGVyZSBtYXkgYmUgYnVncywgaW5jb21wbGV0ZVxuZmVhdHVyZXMsIGluY29ycmVjdCBkb2N1bWVudGF0aW9uLCBvciBvdGhlciBkaXNjcmVwYW5jaWVzLlxuXG5JZiB5b3UgZGlkbid0IHByb3ZpZGUgYSB2YWx1ZSBmb3IgYGhvc3Qtdm9sdW1lYCBpbiB0aGUgQ0xJLFxuWU9VUiBEQVRBIFdJTEwgTk9UIEJFIFNBVkVEIElOIEFOWSBXQVkuXG4iLCJpbWFnZXMiOnsiaWNvbi1zbWFsbCI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1zbWFsbC5wbmciLCJpY29uLW1lZGl1bSI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1tZWRpdW0ucG5nIiwiaWNvbi1sYXJnZSI6Imh0dHBzOi8vZG93bmxvYWRzLm1lc29zcGhlcmUuY29tL3VuaXZlcnNlL2Fzc2V0cy9pY29uLXNlcnZpY2UtamVua2lucy1sYXJnZS5wbmciLCJzY3JlZW5zaG90cyI6bnVsbH19",
        "DCOS_PACKAGE_REGISTRY_VERSION": "2.0",
        "DCOS_PACKAGE_FRAMEWORK_NAME": "jenkins",
        "DCOS_PACKAGE_VERSION": "0.2.3",
        "DCOS_PACKAGE_NAME": "jenkins",
        "MARATHON_SINGLE_INSTANCE_APP": "true",
        "DCOS_PACKAGE_IS_FRAMEWORK": "true",
        "HAPROXY_0_VHOST": "myhostname.westus.cloudapp.azure.com/"
    },
    "portDefinitions": [
        {
            "port": 10101,
            "protocol": "tcp",
            "labels": {}
        },
        {
            "port": 10103,
            "protocol": "tcp",
            "labels": {}
        }
    ],
    "upgradeStrategy": {
        "minimumHealthCapacity": 0,
        "maximumOverCapacity": 0
    }
}`

I'm running DC/OS v.1.7.1. I do get the error from inside the jenkins logs. I'm running azure on a shared folder which is mapped from azure file storage.

**Comment by rji** [comment]
The `Operation not supported` message comes from the kernel and usually points at a permissions problem on the underlying storage.

Please provide information from `docker info`, as well as information about the operating system (such as `uname -a`, operating system distribution, and release).

**Comment by rji** [comment]
It appears this ticket is stale; there hasn't been any activity in the last 30 days. Please reopen with the requested information if this was in error.
